const $=id=>document.getElementById(id),KEY='family-pillbox-b-v2';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let plan=null,drafts=[],epoch=0;const day=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.version===2&&Array.isArray(x.tasks))plan=x;}catch{}
function msg(s){$('message').textContent=s;$('message').style.display=s?'block':'none';}
function save(){try{localStorage.setItem(KEY,JSON.stringify(plan));return true;}catch{msg('存储失败，本次操作仅保留在页面内，请导出记录。');return false;}}
function ask(text){return new Promise(resolve=>{const layer=document.createElement('div');layer.className='confirm-layer';const card=document.createElement('article');card.setAttribute('role','dialog');card.setAttribute('aria-label','操作确认');const p=document.createElement('p');p.textContent=text;for(const [name,value]of [['确认操作',true],['取消',false]]){const b=document.createElement('button');b.textContent=name;b.onclick=()=>{layer.remove();resolve(value);};card.append(b);}card.prepend(p);layer.append(card);document.body.append(layer);});}
function art(t){if(/^data:image\/(png|jpeg|webp);base64,/.test(t.photo||''))return `<img class="medicine-photo" src="${esc(t.photo)}" alt="${esc(t.name)}实物参考照片">`;return `<div class="medicine-art" role="img" aria-label="虚构药品外观示意"><svg width="150" height="85" viewBox="0 0 150 85"><rect x="12" y="8" width="75" height="65" rx="8" fill="#e6efe9" stroke="#14695f"/><path d="M22 25h55M22 36h40" stroke="#14695f" stroke-width="4"/><ellipse cx="115" cy="52" rx="20" ry="13" fill="white" stroke="#14695f" stroke-width="2"/><path d="M115 40v24" stroke="#14695f"/></svg><span>虚构示意 · 不用于识药</span></div>`;}
const names={pending:'等待服药后确认',done:'父母本人确认已服药',unsure:'记不清是否服用',missing:'找不到药',help:'需要电话核对'};
function render(){
 $('summary').hidden=true;$('consent').checked=!!plan?.consent;$('wait').value=String(plan?.waitMinutes||30);$('clock').textContent=plan?`${plan.clock.replace('T',' ')} · ${plan.online?'在线 Mock':'离线 Mock'}`:'尚无任务';
 if(!plan){$('tasks').innerHTML='<div class="empty">先载入样例，或填写并核对已有安排。</div>';$('childContent').textContent='暂无家庭记录。';$('aiArea').hidden=true;return;}
 const active=plan.reminders.filter(r=>plan.tasks.find(t=>t.id===r.taskId)?.status==='pending');$('reminder').hidden=!active.length;$('reminder').textContent=active.length?`🔔 ${active.at(-1).type==='repeat'?'再次提醒':'到点提醒'}：${active.at(-1).text}`:'';
 $('tasks').innerHTML=plan.tasks.map(t=>{const due=new Date(plan.clock)>=new Date(`${plan.day}T${t.time}:00`),opened=plan.signals.some(s=>s.taskId===t.id&&s.correct);return `<article class="dose-card"><div class="dose-head"><span class="badge ${t.status}">${names[t.status]}</span><strong>${esc(t.time)}</strong></div><div class="dose-layout">${art(t)}<div><h3>${esc(t.name)} · 每次 ${esc(t.dose)}</h3><p class="slot ${due&&t.status==='pending'?'lit':''}">💡 ${esc(t.slot)} ${due&&t.status==='pending'?'· 此药格亮灯 Mock':''}</p><p>外观参考：${esc(t.appearance)}</p><p class="method">已有吃法：${esc(t.method)}</p><p class="muted">安排核对人：${esc(plan.checkedBy)} · ${opened?'有对应药格打开记录':'尚无对应药格打开记录'}</p></div></div><div class="actions"><button data-id="${t.id}" data-action="voice" class="secondary">朗读本次指引</button><button data-id="${t.id}" data-action="open" class="secondary">打开对应药格（Mock）</button><button data-id="${t.id}" data-action="wrong" class="secondary">试试打开错误药格</button><button data-id="${t.id}" data-action="done" ${!due||t.status==='done'?'disabled':''}>我已按提示服药</button></div><div class="actions"><button data-id="${t.id}" data-action="missing" class="secondary">找不到药</button><button data-id="${t.id}" data-action="unsure" class="secondary">记不清是否服用</button><button data-id="${t.id}" data-action="help" class="secondary">需要孩子电话核对</button></div></article>`;}).join('');
 $('aiArea').hidden=!plan.consent;if(!plan.consent){$('childContent').innerHTML='<div class="empty">父母尚未授权或已撤回分享。消息和状态已隐藏。</div>';return;}
 const issues=FamilyCore.issues(plan);
 $('childContent').innerHTML=`<div class="notice">确认依据：父母本人确认 + 对应药格打开记录 + 时间。不能证明实际吞服；缺少确认也不等于漏服。</div><h3>今日状态</h3>${plan.tasks.map(t=>`<article class="status-row"><strong>${esc(t.time)} ${esc(t.name)}</strong><span>${names[t.status]}</span><p class="muted">${t.confirmedAt?'本人确认时间：'+esc(t.confirmedAt.replace('T',' ')):'尚无本人服药确认'} · 对应药格：${plan.signals.some(s=>s.taskId===t.id&&s.correct)?'有打开记录':'无打开记录'}</p></article>`).join('')}<h3>短信消息箱（Mock · 未实际发送）</h3>${[...plan.notifications].reverse().map(n=>`<article class="sms"><span class="badge">${n.type==='confirmed'?'服药确认':n.type==='overdue'?'未确认提醒':n.type==='offline'?'设备异常':'父母求助'}</span><p>${esc(n.text)}</p><small>${esc(n.at.replace('T',' '))} · ${esc(n.channel)}</small></article>`).join('')||'<p>暂无消息。正常确认后发送确认消息；未确认达到等待窗口时发送联系提醒。</p>'}<h3>当前需要联系</h3>${issues.map(x=>`<article><p>${esc(x.text)}</p><button data-call="${esc(x.id)}" class="secondary">模拟电话联系父母</button><label>联系后的备注<textarea data-note="${esc(x.id)}" rows="2" placeholder="填写实际核对结果"></textarea></label><button data-follow="${esc(x.id)}">保存跟进</button></article>`).join('')||'<p>当前无待联系事项。</p>'}<h3>联系历史</h3>${plan.followups.map(x=>`<p>${esc(x.at.replace('T',' '))} · ${esc(x.note)}</p>`).join('')||'<p>暂无跟进。</p>'}`;
}
function changed(){const before=plan.reminders.length;FamilyCore.evaluate(plan);if(plan.reminders.length>before)chime();save();render();}
$('parentView').onclick=()=>{$('parent').hidden=false;$('child').hidden=true;render();};$('childView').onclick=()=>{$('parent').hidden=true;$('child').hidden=false;render();};
$('demo').onclick=async()=>{if(plan&&!await ask('替换现有演示记录？'))return;plan=FamilyCore.make(day(),[{name:'示例药A（虚构）',dose:'1片',times:['08:00','20:00'],slot:'左侧1号药格',appearance:'绿色示例外盒，白色圆片（示意）',method:'按已核对的示例安排，用水口服。此吃法仅为虚构演示。'}],'父母与子女（样例）');changed();msg('样例从07:59开始。父母授权后，推进1分钟体验到点提醒。');};
$('consent').onchange=()=>{if(!plan)return;$('summary').textContent='';plan.consent=$('consent').checked;changed();};$('wait').onchange=()=>{if(plan){plan.waitMinutes=Number($('wait').value);changed();}};
for(const [id,min]of [['minute',1],['quarter',15],['hour',30]])$(id).onclick=()=>{if(!plan)return msg('请先载入样例');plan.clock=new Date(new Date(plan.clock).getTime()+min*60000).toLocaleString('sv-SE').replace(' ','T');changed();msg('演示时钟已推进；所有提醒和短信均为本机模拟。');};
$('offline').onclick=()=>{if(plan){plan.online=false;changed();msg('离线时暂停逐药提醒推断，向已授权子女显示设备异常。');}};$('sync').onclick=()=>{if(plan){plan.online=true;changed();msg('同步恢复；重新核对当前任务状态。');}};
$('tasks').onclick=async e=>{const {id,action}=e.target.dataset;if(!action||!plan)return;const t=plan.tasks.find(x=>x.id===id);try{if(action==='voice'){const text=FamilyCore.instruction(t);if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='zh-CN';speechSynthesis.speak(u);}return msg(`语音指引文本：${text}（实际发声取决于设备语音支持）`);}if(action==='open'||action==='wrong'){const ok=FamilyCore.open(plan,id,action==='open'?t.slot:'错误药格');save();render();return msg(ok?'对应药格已打开。请按已有安排核对并实际服药后，再本人确认。':'打开了错误药格，请停下并核对亮灯药格。没有更新服药状态。');}if(action==='done'){if(!await ask('请核对药格、药品和剂量。确认本人已按已确定的指引实际服药？'))return;FamilyCore.confirm(plan,id);changed();return msg(plan.consent?'本人确认已保存，子女消息箱新增一条短信 Mock。':'本人确认已保存；未授权，因此未生成子女消息。');}FamilyCore.help(plan,id,action);changed();msg('求助状态已记录；授权时子女收到求助消息 Mock。');}catch(err){msg(err.message);}};
$('childContent').onclick=e=>{const {call,follow}=e.target.dataset;if(call){plan.followups.push({id:call,at:plan.clock,note:'模拟电话联系（未实际拨号，未判断服药结果）'});save();render();return msg('已记录电话联系 Mock，没有实际拨号。');}if(follow){const f=[...document.querySelectorAll('[data-note]')].find(n=>n.dataset.note===follow);if(!f.value.trim())return msg('请填写沟通结果');plan.followups.push({id:follow,at:plan.clock,note:f.value.trim()});save();render();msg('已保存跟进，父母服药状态保持原样。');}};
$('summarize').onclick=()=>{$('summary').textContent=FamilyCore.summary(plan);$('summary').hidden=false;};
function draftRender(){$('confirmed').checked=false;$('confirmArea').hidden=!drafts.length;$('draft').innerHTML=drafts.map((d,i)=>`<article class="draft" data-i="${i}">${[['name','药品名称'],['dose','每次剂量'],['times','明确时刻（逗号分隔）'],['slot','药格位置'],['appearance','外盒及药片外观描述'],['method','已有方案明确的吃法']].map(([k,label])=>`<label>${label}<input data-field="${k}" value="${esc(k==='times'?d.times.join(','):d[k])}"></label>`).join('')}<label>实物参考照片（仅本机，PNG/JPEG/WebP，最大1MB）<input data-photo="${i}" type="file" accept="image/png,image/jpeg,image/webp"></label><p>${d.photo?'已选择实物参考照片':'未上传照片，将显示虚构示意图'}</p></article>`).join('');}
function syncDraft(){document.querySelectorAll('.draft').forEach(n=>{const d=drafts[+n.dataset.i];n.querySelectorAll('[data-field]').forEach(f=>d[f.dataset.field]=f.dataset.field==='times'?f.value.split(/[,，、\s]+/).filter(Boolean):f.value.trim());});}
$('draft').oninput=()=>{$('confirmed').checked=false;};$('checkedBy').oninput=()=>{$('confirmed').checked=false;};$('draft').onchange=async e=>{if(e.target.dataset.photo===undefined)return;const f=e.target.files[0];if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>1024*1024)return msg('请选择1MB以内的PNG/JPEG/WebP照片');syncDraft();const d=drafts[+e.target.dataset.photo],token=epoch;const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f);});if(token!==epoch)return;d.photo=data;draftRender();};
$('manual').onclick=()=>{epoch++;syncDraft();drafts.push({name:'',dose:'',times:[],slot:'',appearance:'',method:''});draftRender();};$('input').oninput=()=>{epoch++;drafts=[];draftRender();};
$('extract').onclick=async()=>{const text=$('input').value.trim();if(!text)return msg('先输入已有安排');const version=++epoch;drafts=[];draftRender();$('extract').disabled=true;try{let x;if(staticMode){if(text.length>4000)throw Error('请输入 1–4000 字的已有安排。');x=window.Extract.extractMock(text);}else{const r=await fetch('api/extract',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});x=await r.json();if(!r.ok)throw Error(x.error);}if(version!==epoch)return;drafts=x.items.map(x=>({...x,slot:'',appearance:'',method:''}));draftRender();msg('AI只提取已有药名、剂量和明确时刻。位置、外观和吃法请按实物与原安排补齐核对。');}catch(e){if(version===epoch)msg(e.message);}finally{$('extract').disabled=false;}};
$('create').onclick=async()=>{if(!$('confirmed').checked)return msg('请先核对并勾选确认');syncDraft();try{const next=FamilyCore.make(day(),drafts,$('checkedBy').value);if(plan&&!await ask('启用新安排并替换当前演示记录？'))return;plan=next;drafts=[];draftRender();changed();msg('已启用今日安排，请父母主动授权分享。');}catch(e){msg(e.message);}};
$('export').onclick=()=>{if(!plan)return;const u=URL.createObjectURL(new Blob([JSON.stringify(plan,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='安心药箱_B_用药确认记录.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
let staticMode=false;
fetch('api/status').then(r=>r.json()).then(s=>$('mode').textContent=s.mode==='mock'?'安排提取：规则Mock；指引与摘要：AI Mock。':'提取使用已配置服务；输入会发送至该服务。指引与摘要仍为Mock。').catch(()=>{staticMode=true;$('mode').textContent='在线静态版：安排提取在浏览器内用规则Mock完成，不发送到任何服务；指引与摘要为AI Mock。';});render();

function chime(){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const c=new A(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=660;g.gain.setValueAtTime(0.08,c.currentTime);g.gain.exponentialRampToValueAtTime(0.001,c.currentTime+0.5);o.start();o.stop(c.currentTime+0.5);o.onended=()=>c.close();}catch{}}
