(function(root){
 const stamp=p=>new Date(p.clock).toLocaleString('zh-CN',{hour12:false});
 function notify(p,type,t,text){if(!p.consent)return;const key=`${t?.id||'device'}:${type}:${t?.revision||0}`;if(p.notifications.some(n=>n.key===key))return;p.notifications.push({key,type,taskId:t?.id||null,text,at:p.clock,channel:'短信 Mock'});}
 function evaluate(p){
  if(!p.online){notify(p,'offline',null,'药箱离线，当前记录可能未同步。请先核对设备和父母情况，不能据此判断未服药。');return;}
  for(const t of p.tasks){if(t.status!=='pending')continue;const mins=(new Date(p.clock)-new Date(`${p.day}T${t.time}:00`))/60000;if(mins>=0&&!t.reminded){t.reminded=true;p.reminders.push({taskId:t.id,at:p.clock,type:'due',text:instruction(t)});}if(mins>=p.repeatMinutes&&!t.repeated){t.repeated=true;p.reminders.push({taskId:t.id,at:p.clock,type:'repeat',text:instruction(t)});}if(mins>=p.waitMinutes)notify(p,'overdue',t,`${t.time} ${t.name}：超过约定${p.waitMinutes}分钟仍未收到本人确认，请联系核对。未确认不等于未服药。`);}
 }
 function instruction(t){return `请核对 ${t.slot} 的 ${t.name}，每次 ${t.dose}。已有吃法：${t.method.replace(/[。；;]+$/, "")}。服药后请按“我已按提示服药”。`;}
 function open(p,id,slot){const t=p.tasks.find(t=>t.id===id);if(!t)throw Error('任务不存在');const correct=slot===t.slot;p.signals.push({taskId:id,slot,correct,at:p.clock});return correct;}
 function confirm(p,id){const t=p.tasks.find(t=>t.id===id);if(!p.online)throw Error('设备离线，请先模拟恢复同步再确认。');if(new Date(p.clock)<new Date(`${p.day}T${t.time}:00`))throw Error('这次任务尚未到点。');if(!p.signals.some(s=>s.taskId===id&&s.correct))throw Error('请先打开并核对对应药格。');if(t.status==='done')return;t.events.push({from:t.status,to:'done',at:p.clock});t.status='done';t.confirmedAt=p.clock;notify(p,'confirmed',t,`${t.time} ${t.name}：父母于${stamp(p)}本人确认已按提示服药；记录到对应${t.slot}打开。此消息不证明实际吞服。`);}
 function help(p,id,status){const t=p.tasks.find(t=>t.id===id);t.events.push({from:t.status,to:status,at:p.clock});t.status=status;delete t.confirmedAt;t.revision=(t.revision||0)+1;notify(p,'help',t,`${t.time} ${t.name}：父母选择“${status==='unsure'?'记不清是否服用':status==='missing'?'找不到药':'需要电话帮忙核对'}”，请联系。`);}
 function issues(p){if(!p.consent)return [];if(!p.online)return [{id:'offline',text:'设备离线，请先核对同步情况。'}];return p.tasks.filter(t=>['unsure','missing','help'].includes(t.status)||(t.status==='pending'&&new Date(p.clock)-new Date(`${p.day}T${t.time}:00`)>=p.waitMinutes*60000)).map(t=>({id:t.id,text:`${t.time} ${t.name}：${t.status==='pending'?'超时未确认':t.status==='unsure'?'记不清是否服用':t.status==='missing'?'找不到药':'需要电话核对'}`}));}
 function summary(p){if(!p.consent)return '父母未授权分享。';const list=issues(p);return `【AI Mock】今日有${p.tasks.filter(t=>t.status==='done').length}条本人服药确认，${list.length}项待核对。${list.length?'沟通开场：现在方便一起核对药箱提示吗？':'当前无须逐次电话询问。'}\n依据：${list.map(x=>x.text).join('；')||'当前任务记录无待核对事项'}\n药格打开和本人确认仍不能证明实际吞服。`;}
 function make(day,items,checkedBy){if(!checkedBy.trim())throw Error('请填写安排核对人');if(!items.length)throw Error('至少录入一项');const tasks=[];items.forEach((x,i)=>{for(const k of ['name','dose','slot','method','appearance'])if(!x[k]?.trim())throw Error('请补齐药名、剂量、药格、吃法和外观信息，AI不会猜测。');if(!x.times.length||x.times.some(t=>!/^([01]\d|2[0-3]):[0-5]\d$/.test(t))||new Set(x.times).size!==x.times.length)throw Error('请核对明确时刻，不能重复');for(const time of x.times)tasks.push({...x,id:`${i}-${time}`,time,status:'pending',events:[],revision:0,reminded:false,repeated:false});});return {version:2,day,clock:`${day}T07:59:00`,consent:false,online:true,waitMinutes:30,repeatMinutes:15,checkedBy:checkedBy.trim(),tasks,signals:[],reminders:[],notifications:[],followups:[]};}
 const api={evaluate,open,confirm,help,issues,summary,make,instruction};if(typeof module!=='undefined')module.exports=api;else root.FamilyCore=api;
})(typeof window!=='undefined'?window:globalThis);


